### ISSUE TITLE
Enhance ability to use checkbox or radio as the first dependent parent

### ISSUE THREAD

**Issue by Mamadou208** [kartik-v/dependent-dropdown#10]
Hallo Kartik,

My colleague and I made a small change in the vendor/dependent-dropdown/js/dependent-dropdown.js to make it work with a RADIO BUTTON. 
This is our change at line 185 to :
<pre><code>
        setDependency: function ($id, depends, len, vInitVal) {
               ------------------------------------------------------
                if (!$('#' + depends[j]).is(':input')){
                   var $el = $('#' + depends[j] + ' input:checked');
                } 
           --------------------------------------------------
            }
           
        }
</code></pre>
Would you mind, having a look at if is ok for you ?
If it is OK would you like to add this into the next commit of your code otherwise can you tell us how to override the setDependency in our code?

**Comment by kartik-v** [comment]
Resolved via upgrade to release v1.4.0.
