### ISSUE TITLE
Sticky values for dependent drop downs

### ISSUE THREAD

**Issue by Alan01252** [kartik-v/dependent-dropdown#13]
Hi Kartik-v :)

Please can you help, I have the following scenario:

- User selects option 3 from initial drop down
- Dependent drop down is populated
- User selects option 6 from dependent drop down
- User submits form and is returned to the same page page

- Initial drop down has "selected" set to option 3 correctly
- Dependent drop down is populated correctly with options based on option 3
- Dependent drop down does not default to option 6 as selected

Hacking the JSON response to have "selected": 6 , still does not set the option correctly, although this does work for subsequent changes of the initial select box.

Please help :)

Alan

**Comment by ToRvaLDz** [comment]
Same problem here

**Comment by kartik-v** [comment]
Depends on your code that submits the form and renders the dependent dropdown. You may need to check that and see whether you are telling the plugin to initialize using AJAX or you are doing it manually. If manually you need to set  an initial value for each dropdown.

**Comment by ToRvaLDz** [comment]
I solved setting the child-2 val on this event:

$('#child-2').on('depdrop.afterChange', function(event, id, value) {
   $('#child-2').val(xx).change();
});

**Comment by newerton** [comment]
The query in ajax is very fast, as 'initialize' is true.
 The 3rd dropdown rescues 'depdrop_parents [0]: Loading ...'.
 Need a millisecond delay, or seguencial implementation;

**Comment by kartik-v** [comment]
The ajax requests are already sequential - called after completion of the dependent parent request.
