### ISSUE TITLE
DepDrop with dynamic fields?

### ISSUE THREAD

**Issue by albertborsos** [kartik-v/dependent-dropdown#19]
I would like to make a form, with fields, which depends dynamically from another fields. This is almost possible, but I can not handle it at the backend side.

I have an item which has dynamic properties. Example: A t-shirt which has size and color. The size and the color is a property, which has an id (34, 53) and these has possible values (`S`,`M`, `L`... - `black`-`white`). So when the request sent I get values at the backend like `S` or `black`, but I do not know this value relates to which property, because in the `parents` i only get `parents[0]` and `parents[1]`.

It would be possible to send the parents with an associative array? So when i can set the `depends` attribute like
 ```php
'depends' => [
    34 => 'item-property-34',
    53 => 'item-property-53'
]
```
instead of:
 ```php
'depends' => [ 
    'item-property-34',
    'item-property-53'
]
```
So then at the backend I will get this in $_POST['depdrop_parents']:
```php
[
    '34' => 'M',
    '54' => 'black',
]
```
instead of
```php
[
    0 => 'M',
    1 => 'black',
]
```

I am curious what do you think about it!

**Comment by kartik-v** [comment]
This will need change within the jquery plugin. 

The only issue is this change will break BC... for others who have already configured the plugin. Will need to think through this.

**Comment by albertborsos** [comment]
If it would be possible to set normal (like now) and associative arrays to the `depends` and maybe the `params` attributes it will be compatible backward.

**Comment by kartik-v** [comment]
You can now get the updated code on dev-master.

A new property `depdrop_all_params` will be sent to the server ajax action as an associative array with the key being the element id and value being the element value. This will merge the `depdrop_parents` and `depdrop_params` together in an associative array form.

**Comment by kartik-v** [comment]
Resolved via latest commit. You can now get the updated code on dev-master.

A new property `depdrop_all_params` will be sent to the server ajax action as an associative array with the key being the element id and value being the element value. This will merge the `depdrop_parents` and `depdrop_params` together in an associative array form.

**Comment by albertborsos** [comment]
Nice solution, works fine. Thank you!
