### ISSUE TITLE
setting "initialize":true returns  property length of undefined error

### ISSUE THREAD

**Issue by Jrizzi1** [kartik-v/dependent-dropdown#21]
using ver 1.4.1

**Comment by kartik-v** [comment]
Can you ensure you have the latest version and update.

**Comment by Jrizzi1** [comment]
I made sure, [i even created this jsfiddle](http://jsfiddle.net/rkr4LLeh/)
notice the console log gives uncaught type error: cannot read  property length of undefined due to initialize being set to true

commenting out that line will no longer cause that error to occur

**Comment by kartik-v** [comment]
First - ensure you have the updated code. Cross check with dev-master on this repo.

Secondly, on the fiddle I am not sure if the json response is not getting returned correctly.

If you test and return your `getCat2` and `getCat3` json responses from a proper web server via PHP or similar then it should work. 

If you need to see a working example of setting initialize as true- [check scenario # 3 on this demo site](http://demos.krajee.com/widget-details/depdrop#advanced-usage)

**Comment by jimmybaker** [comment]
I'm seeing the same problem. In my case I'm using attributes on the select element to initialize the plugin and I still get the same error message.
