### ISSUE TITLE
Question about isEmpty condition

### ISSUE THREAD

**Issue by Shin1gami** [kartik-v/dependent-dropdown#25]
In your `dependent-dropdown.js` on line `68` there is this particular code:
```
if (!isEmpty($id.data('select2')) && e.type === 'change') {
    return false;                                          
}
```
My question is, why `isEmpty` has to be negative? Because when i've updated this plugin via composer, all my forms were broken.

**Comment by kartik-v** [comment]
- The condition is applicable only if you are using Select2 plugin 
- If you are using `yii2-widget-select2` extension then you MUST have the latest release of that extension as well.
- Note that `yii2-widget-select2` latest release has some major changes from earlier versions
- Check docs and demos for the extensions to understand the code changes (else your code maybe broken).
