### ISSUE TITLE
Ability to configure and extend ajax settings

### ISSUE THREAD

**Issue by kshtayat** [kartik-v/dependent-dropdown#29]
Can you change the setting to give use the ability to control the type of ajax request ?
Not the only allowed type is POST

**Comment by kshtayat** [comment]
Any updates on this ?

**Comment by kartik-v** [comment]
Will evaluate and consider it...

**Comment by kartik-v** [comment]
Resolved via [upgrade to release v1.4.4](https://github.com/kartik-v/dependent-dropdown/commit/a13970aec78e8eaae5cb9f1168df20d443f95113).
