### ISSUE TITLE
Dropdown  at update

### ISSUE THREAD

**Issue by lexen77** [kartik-v/dependent-dropdown#31]
Hi, can you help me please ?
A value of depended dropdowns are not set when the first dropdown has a value. This is my code:

<?php
$id_cappella=117;
$id_piano=9;
$id_loculo=1;        
?>

            <?=Select2::widget([
                                    'name' => 'id_cappella',
                                    'value' => $id_cappella,
                                    'data' => ArrayHelper::map(\app\models\Cappella::find()->all(),'id_cappella','cappella'),
                                    'options' => [
                                                   'multiple' => false, 
                                                   'placeholder' => '---- Seleziona ----',
                                                   'id'=>'id_cappella',
                                                 ],
                                    'pluginOptions' => ['allowClear' => true,'initialize' => true,],             
                                ])  
             ?>

           <?php echo DepDrop::widget([ 
                                        'name' => 'id_piano',
                                        'value'=>$id_piano,
                                        'options' => ['id'=>'id_piano'],
                                        'pluginOptions' => [
                                                            'depends'=> ['id_cappella'],
                                                            'placeholder' => '---- Seleziona ----',
                                                            'url' => Url::to(['piani'])
                                                           ],
                                    ]);  
           ?>
                  

                 <?= $form->field($model, 'id_loculo')->widget(DepDrop::classname(), ['value'=>$id_loculo,
                                                                                    'pluginOptions'=>
                                                                                                    [   
                                                                                                        'depends'=>['id_cappella', 'id_piano'],
                                                                                                        'placeholder' => '---- Seleziona ----',
                                                                                                        'initialize'=> true,
                                                                                                        'url'=>Url::to(['loculi'])
                                                                                                    ]
                                                                                ]);    
                  ?>

**Comment by kartik-v** [comment]
You may want to debug your code. If you need programming tips and help a new Q & A forum has been created for such use and you can [search and ask for questions/help out there](http://webtips.krajee.com/questions).
