### ISSUE TITLE
Make all parameter names configurable

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/dependent-dropdown#34]
Followin properties enabled and added for configuration of all parameters in the plugin

        idParam: 'id',
        nameParam: 'name',
        optionsParam: 'options',
        parentParam: 'depdrop_parents',
        otherParam: 'depdrop_params',
        allParam: 'depdrop_all_params',

**Comment by kartik-v** [comment]
Resolved via [upgrade to release v1.4.4](https://github.com/kartik-v/dependent-dropdown/commit/a13970aec78e8eaae5cb9f1168df20d443f95113).

**Comment by Oxicode** [comment]
+1
