### ISSUE TITLE
Dropdown disappears when clicking on input field

### ISSUE THREAD

**Issue by summerknight** [kartik-v/dependent-dropdown#37]
Everything was ok. I updated composer. Here are some updates from logs.

Removing kartik-v/dependent-dropdown (v1.4.3)          
  - Installing kartik-v/dependent-dropdown (v1.4.4)

 - Removing kartik-v/yii2-krajee-base (v1.7.9)
  - Installing kartik-v/yii2-krajee-base (v1.8.0)
    Downloading: 100%         

After it a dropdown usability is decrease. Here is a life example https://eduguide.ru/spisok-vuzov

When you click on arrow - dropdown is ok.
But when you click on field - dropdown appears and suddenly disappears.

Also dropdown become to appear on the middle of input field. Not on bottom of it as before.

What is it? How to fix it?

**Comment by kartik-v** [comment]
I do not see any problem. You may need to check if you have caching issues on your browser.
