### ISSUE TITLE
Data Attributes do not work

### ISSUE THREAD

**Issue by sanketpanaskar** [kartik-v/dependent-dropdown#42]
Hi, data attributes does not work with this.

where as if i use function depdrop using element id it works.

**Comment by sanketpanaskar** [comment]
<select id="dateTime<%=count%>"  class="depdrop" data-depends="['city<%=count%>']" data-url="/exam/getAvailableCentersForCity">
<option id="">Select ...</option>
</select>

**Comment by Chouhada** [comment]
The data attributes do seem to be broken.

Using the example from the documentation, the depdrop class doesn't seem to work properly. I think there is also a typo in the docs:
`depends="['parent-1, 'child-1']"`
Which I assume should be
`depends="['parent-1', 'child-1']"`

Not that this fixes the issue.

Using javascript  from the second example works though.

**Comment by kartik-v** [comment]
[Read this](http://stackoverflow.com/questions/27940973/html5-data-attributes-how-to-modify-array-of-data-attached-to-dom-element). You may need to use double quotes inside and escape it as `&quot;`.

**Comment by Chouhada** [comment]
That did it - Thank you. I can now get the example from the documentation working (well,sending the HTTP request now anyway!)

For anyone else who experiences this issue, my line now looks like:

`    <select id="child-1" class="depdrop" data-depends="[&quot;parent-1&quot;]" data-url="http://path/to/child_1_list">
`

This sends the request according to my browser, where previously it didn't.
