### ISSUE TITLE
Possible to load a text input when a previous selector value === a value?

### ISSUE THREAD

**Issue by jasondavis** [kartik-v/dependent-dropdown#45]
I have this setup with 3 dropdowns...
## Selection 1
- Form submit  
- Link Click  
## Selection 2

`if selection 1 === 'Form Submit'`  
- Gravity Forms  
- Ninja Forms  
- Contact 7 Forms  
- Other Form by Name Attribute  
- Other Form by Class Attribute  
- Other Form by ID Attribute  

`if selection 1 === 'Link Click'`  
- Link CSS ID  
- Link CSS Class  
## Selection 3

`if a named form from selection 2 is selected then we load a list of Forms from the DB`  

if any of the 3 "Other Form" values or the 2 "Link" values are selected in selection 2....then we need to somehow show a text input instead of a selection dropdown for selection 3!

---

Any idea how this might be accomplished with the library?
-

**Comment by jasondavis** [comment]
I got a partial solution so far doing this...

Next to my selection dropdown which should sometimes be a dropdown and sometimes be a text input filed I have added a text input and set its displau to none/hidden:

`<input type="text" name="Account[lev-2]" id="account-lev-2-input" value="">`

Next I used the library's `afterChange` event to get the value from the previous dropdown in which I then can alternate showing and hiding the last dropdown and input fields...
```
$('#account-lev-2').on('depdrop.afterChange', function(event, id, value) {
    console.log(value);
    if(value === 'other_form_class'){
        $('#account-lev-2').hide();
        $('#account-lev-2-input').show();
    }else{
        $('#account-lev-2').show();
        $('#account-lev-2-input').hide();
    }
});
```

So this somewhat looks like it is a start to a solution.

The harder part now is to have it handle previous saved data which will need to decide which one should show on page load.

**Comment by kartik-v** [comment]
Not sure if I see an issue with the plugin. If it is more to do with programming help you may post queries on the forum and discussions section.
