### ISSUE TITLE
Parent 'select all' option does not trigger ajax for dependent field.

### ISSUE THREAD

**Issue by guarniello** [kartik-v/dependent-dropdown#52]
If using parent field as a select2 with multiple select enabled, option to 'select all' does not trigger ajax and dependent field is not updated/populated.

**Comment by kartik-v** [comment]
You must select a single value for dependent dropdown to execute the dependency.

**Comment by fateevv85** [comment]
or you can modify dependent-dropdown.js on line 97 like:
on('depdrop:change change select2:select krajeeselect2:cleared krajeeselect2:selectall krajeeselect2:unselectall'
