### ISSUE TITLE
Q: Upgrade to 1.4.5

### ISSUE THREAD

**Issue by jesusvallez** [kartik-v/dependent-dropdown#55]
I am trying to upgrade my dependent-dropdown to 1.4.5 and I get this error:

![image](https://cloud.githubusercontent.com/assets/19146593/22882767/07a180dc-f1ed-11e6-8e36-b010f1638b57.png)

Is this version published? Or is in github only?

![image](https://cloud.githubusercontent.com/assets/19146593/22883238/7911858a-f1ef-11e6-9408-f585e0bb4086.png)

**Comment by kartik-v** [comment]
Release v1.4.5 is not tagged yet and will be done... you can get this release from dev-master in the interim.
