### ISSUE TITLE
JavaScript error when trying to access model on update

### ISSUE THREAD

**Issue by cgsmith** [kartik-v/dependent-dropdown#57]
I am going to `site/update?id=1` with a parent dropdown and one child. 

In the console I get this error [referencing this line](https://github.com/kartik-v/dependent-dropdown/blob/master/js/dependent-dropdown.js#L230)

`Uncaught TypeError: Cannot read property 'apply' of undefined (dependent-dropdown.js:219)`

### How-to duplicate

```php
// _form.php file
    echo $form->field($quote, 'customer_id', ['attribute'=>'Customer'])->dropDownList($activeCustomers, [
        'id'=>'customer-id',
        'prompt'=>'Select Customer'
    ]);

    // Dependent dropdown
    echo $form->field($quote, 'contact_id')->widget(DepDrop::classname(), [
        'options'=>['id'=>'subcat-id'],
        'pluginOptions'=>[
            'depends'=>['customer-id'],
            'placeholder'=>'Select...',
            'url'=> Url::to(['/contacts/subcat'])
        ]
    ]);
```

```php
// ContactsController.php

	/**
	 * Return a list of contacts for multi dropdowns (sub category dropdowns)
	 */
    public function actionSubcat() {
		$out = [];
		if (isset($_POST['depdrop_parents'])) {
			$parents = $_POST['depdrop_parents'];
			if ($parents != null) {
				$cat_id = $parents[0];
				$out = Contacts::find()->where(['customer_id'=>$cat_id])->asArray()->all();
				echo Json::encode(['output'=>$out, 'selected'=>'']);
				return;
			}
		}
		echo Json::encode(['output'=>'', 'selected'=>'']);
	}
```

Any help is appreciated - I checked SO, past issues, and forums. Thank you!

**Comment by kartik-v** [comment]
I am not sure I can debug your code... but one thing I find is you need to check your `$out` generated via `Contacts::find` in your `actionSubcat`  controller action.

You are returning all fields and value as an array... you may need to only return the `id` and `name` - if these fields do not exist  - then edit the `idParam` and `nameParam` in this plugin within `DepDrop::pluginOptions` to be set exactly to the fields you want as the `id` and `name`. On the
