### ISSUE TITLE
Initialize = true problem

### ISSUE THREAD

**Issue by jay-leno** [kartik-v/dependent-dropdown#58]
To start with, I have already updated all of my plugins to the latest available dev-master versions.

I have a scenario where I have 4 dropdowns. However they are not all dependent upon each other as in the Advanced Usage Scenario 3. My scenario is:

drop-0 (direct loaded from db)
drop-1 (direct loaded from db)
drop-2 (direct loaded from db)
drop-3 (dependent on drop-0, drop-1, drop-2)

So drop-3 is dependent on the values chosen in the first three but they aren't dependent on each other. 

All of that works as desired. The only thing that I am having issues with is that on load of an existing record, drop-3 only shows the selected value and not all possible ones. This is with initialize = false by default and initDepends not being set either.

However, if I set "initialize = true" in the plugin options then it will show all possible values but then the value from the db is never actually "selected". If I examine the output being sent back, it shows:

`{"output":[{"id":1,"name":1},{"id":2,"name":2},{"id":3,"name":3}],"selected":2}`

And "2" is the correct value from the db.

**Comment by kartik-v** [comment]
You need to check your application programming logic and why you want to be doing the above setup. With `initialize = true`, with your setup above, you will be firing 3 different ajax requests each for `drop-0`, `drop-1` and `drop-2` and the last request which completes will determine the list of values for `drop-3`. Am closing this as a non-issue - if you need programming help - please post it on the [discussions and comments section of the plugin docs and demos site](http://plugins.krajee.com/dependent-dropdown#comments).
