### ISSUE TITLE
Select2 theme not setting.

### ISSUE THREAD

**Issue by koftikes** [kartik-v/dependent-dropdown#59]
When I try set theme to Select2 nothing happens.
I reserch your code and find the next.
In plugin select2 you expect theme in constructor, but in DepDrop you give it in 'options' in Select2::widget($settings)

So quick solution it's 
```
if (isset($this->options['theme'])) {
    $this->select2Options['theme'] = $this->options['theme'];
}
```

If I am right please fix it, or tell how it should be.
Thank you in advance.

**Comment by kartik-v** [comment]
This is related to yii2-widget-depdrop extension.

Do not set the `theme` property in `DepDrop::options`. Instead set the  `theme` property in `DepDrop::select2Options`
