### ISSUE TITLE
Select2 as DepDrop -> enable multiple select

### ISSUE THREAD

**Issue by pczi** [kartik-v/dependent-dropdown#65]
Hello Kartik,

after debugging the code, I have the following proposals:

(1)
```
getSelect: function (data, placeholder, defVal) {
    var self = this, $select = **$("<select>", {multiple: self.multiple})**, idParam = self.idParam, nameParam = self.nameParam, options;
```

Per default, the newly created select object has "multilpe = false". In this case, the condition is never true in the createOption function if statement ...

(2)
```
createOption = function ($el, id, name, sel, opts) {
    var settings = {value: id, text: name}, strId = id.toString();
    var selids;
    if (sel instanceof Array) {
        if (!$el[0].multiple) { sel = sel.shift(); }
        selids = $.map(sel, function(v, i){ return v.id; });
    } else {
        selids = {sel};
    }
    $.extend(true, settings, (opts || {}));
    if ($.inArray(strId, selids) > -1) {
        settings.selected = "selected";
    }
    $("<option/>", settings).appendTo($el);
};
```

If the "output" is expected in the format [{id: "156",…}, {id: "158",…}], I would also expect "selected" to be in the same format and not just a normal array.

(3)
```
        "kartik-v/dependent-dropdown": "dev-master as 1.4.4",
        "kartik-v/yii2-widget-depdrop": "1.0.4 as 1.0.1",
```
I had to frickle around with composer to have both the latest versions of the dependent-dropdown and the widget-depdrop.

**Comment by vitorarantes** [comment]
+1

**Comment by kartik-v** [comment]
Will be resolved via some updates to be done.
