### ISSUE TITLE
[Reproducable in official docs]Depdrop can't detect select2 value change but it can detect simple dropdown value change :(

### ISSUE THREAD

**Issue by BenasPaulikas** [kartik-v/dependent-dropdown#71]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
https://github.com/kartik-v/yii2-widget-depdrop/issues/32
- [x] The issue still exists against the latest `master` branch of dependent-dropdown.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/dependent-dropdown) and [demos](http://plugins.krajee.com/dependent-dropdown/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Go to http://demos.krajee.com/widget-details/depdrop
2. 
![image](https://user-images.githubusercontent.com/6473565/36697448-aea4179e-1b79-11e8-9d41-f55c757bdf38.png)

3. Change Lev0 valua via javascript: ```$("#account-lev0").val(3).trigger("change")```

## Expected behavior and actual behavior

When I follow those steps, I see...

That child dropdowns are not updated

I was expecting...
Child dropdowns to be updated

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- dependent-dropdown version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/dependent-dropdown/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using dependent-dropdown without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by BenasPaulikas** [comment]
P.S. It only happens if it's select2 :( I think it's not catching change event or something.

**Comment by kartik-v** [comment]
It works fine on the demos page... it is possible you have some browser caching issue loading outdated stale assets.. clear the browser cache and retry.

**Comment by BenasPaulikas** [comment]
I still have this problem :(

In google chrome I have f12 > network > disable cache selected and all cached files removed few mins ago. On page load I see this:

![image](https://user-images.githubusercontent.com/6473565/36753844-f9f623b6-1c39-11e8-983e-0ceea339fbab.png)
I execute javascript. First dropdown is changed but depdrop is not triggered
![image](https://user-images.githubusercontent.com/6473565/36753904-26737290-1c3a-11e8-9bb8-4350f7e943c8.png)

Same with firefox :(

**Comment by BenasPaulikas** [comment]
@kartik-v any ideas ? I still can reproduce this.. :(

**Comment by ricardovigatti** [comment]
+1

**Comment by BenasPaulikas** [comment]
@ricardovigatti no news yet. I will try your solution thank you :)

**Comment by BenasPaulikas** [comment]
@ricardovigatti

select2 destroy method did the job but I think easier solution based on this
https://github.com/kartik-v/dependent-dropdown/blob/master/js/dependent-dropdown.js#L99 

is:

$("#input").val(566).trigger("change").trigger("select2:select")

I don't know if it's a good hack but it does the job :dagger:
