### ISSUE TITLE
Depdropdown doesnot display values from the database

### ISSUE THREAD

**Issue by favourkiiza** [kartik-v/dependent-dropdown#75]
Dependent drop down seems to be working fine only that it only shows blank space instead of values after selecting from the first dropdown. So when i click on that blank space , the post the model is updated, but i cant see the name i have posted, it only shows blank space

![image](https://user-images.githubusercontent.com/30919045/77684089-7cf86b00-6faa-11ea-9dea-5189031aaf73.png)

That is what it shows when i try to select
![2020_03_26_21_44_IMG_4547](https://user-images.githubusercontent.com/30919045/77684752-728aa100-6fab-11ea-8cd9-24d363b38043.JPG)

**Comment by alejandrolorefice** [comment]
I had the same problem and it turned out that I wasn't respecting the specified format provided in [the docs](https://demos.krajee.com/widget-details/depdrop) 
`[
             *      'out'=>[
             *          ['id'=>'<prod-id-1>', 'name'=>'<prod-name1>'],
             *          ['id'=>'<prod_id_2>', 'name'=>'<prod-name2>']
             *       ],
             *       'selected'=>'<prod-id-1>'
             *  
]`
If you map your []ActiveRecord into this format it might be fixed

**Comment by kartik-v** [comment]
Yes refer the [dependent dropdown plugin ajax response format](https://plugins.krajee.com/dependent-dropdown#ajax-response-format) needed from your server action
